# -*- coding: utf-8 -*-
"""week2 homework google .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ykwJmfx8tlMep4f_SI_WU_58eSOV8yVP
"""

print("hello world")

import pandas as pd

pd.Series([10, 20, 30])

