# -*- coding: utf-8 -*-
"""week4 homework .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FnbeX1qNjhthmILGnbm84wwpP7vRNtXv
"""

#work1

tempc=25
tempf=tempc*9/5+32
print(tempf)

#work1

tempf=86
tempc=(tempf-32)*5/9
print(tempc)

#work2

shaq_hei=216
shaq_height=float(int(shaq_hei)/100)
shaq_weight=147


print(shaq_height, type(shaq_height))
print(shaq_weight, type(shaq_weight))

#work2

shaq_bmi=float(shaq_weight)/(float(shaq_height)*float(shaq_height))
print(shaq_bmi, type(shaq_bmi))

#work3

ross_said='''Let's put aside the fact that you "accidentally" pick up my grandmother's ring.'''

print(ross_said)

#work4

space=input("your location is ")
weather=input("How is weather here?")

print("我在", space, "天氣", weather)

#work5

player_name=input("name:")
player_height=float(input("height:"))
player_weight=float(input("weight:"))

player_bmi=player_weight/(player_height*player_height)
print("player is", player_name, "and bmi is {:.2f}".format(player_bmi))
print("是否過重", player_bmi > 30)

#practice

pi=3.1415926
print("{:.0f}".format(pi))

#practice
hours=4
mins=12
mins=mins+hours*60

print(mins)

#practice
hours=int(input("your hours:"))
mins=int(input("your mins:"))
mins+=hours*60

print("total mins is", mins)

