# -*- coding: utf-8 -*-
"""week6 a106260020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYIQ-bpcg7ZkhRmSrZsL_mQeFaFpgJAp
"""

#work1

salary=input("your salary is ")
print(type(salary))
deposit=input("your deposit is ")
print("credit card ans:", int(salary) >=40000 or int(deposit)>=500000)

#work2

num=input("your number:")
ans=int(num) % 2
print(ans == 1)

#餘數=1時，答案是true，所以奇數會是true
#雙數就是false

#work3
