# -*- coding: utf-8 -*-
"""“week3 homework google

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8SBZbVk60KBb6d-QL-qojZt8AAveHZg
"""

movie_title="Advengers: endgame"
movie_length=181
movie_rating=8.4

print(movie_title)
print(movie_length)
print(movie_rating)

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))

